# Default Spring Profile
server:
  error:
    include-message: always
logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
spring:
  data:
    mongodb:
      username: user
      password: pwd
      host: localhost
      port: 27017
      database: exhibition-db
      authentication-database: admin
      auto-index-creation: true
de:
flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5
app:
  gallery-service:
    host: localhost
    port: 7001
  painting-service:
    host: localhost
    port: 7002
  sculpture-service:
    host: localhost
    port: 7003
---
spring:
    config:
      activate:
        on-profile: docker
spring.data.mongodb.host: mongodb
app:
  gallery-service:
    host: gallery-service
    port: 8080
  painting-service:
    host: painting-service
    port: 8080
  sculpture-service:
    host: sculpture-service
    port: 8080
server.port: 8080