@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

title System Context Diagram for Gallery System

Person(employee, "Administrator", "An administrator of the gallery.")
System(system, "Gallery", "Allows gallery administrators to manage the artworks in gallery")

Rel(employee, system, "Track artworks using")
SHOW_LEGEND()
@enduml